Стилизация главной страницы
htmlacademy-htmlcss/1447971-sedona-30 pull request #4
Opened 2021-02-10 12:28 UTC by masha8709

2021-02-10 20:49 UTC, dean992008 requested changes

2021-02-10 20:49 UTC, dean992008 commented on css/style.css
> +  src: url(../fonts/PTSans.woff2), url(../font/PTSans.woff);
https://up.htmlacademy.ru/htmlcss/30/criteries#b14 - `Все названия написаны маленькими буквами и не имеют пробелов` - Файлы нужно назвать с помощью маленких букв.

2021-02-10 20:49 UTC, dean992008 commented on css/style.css
> +a {
Глобальные стили лучше сгрупировать в начале, после блока с перемеными, а потом уже писать стилизацию по классам.

2021-02-10 20:49 UTC, dean992008 commented on index.html
> +      <h1 class="visually-hidden">Путешествие в Седону</h1>
Нужно описать класс `visually-hidden` так чтобы он доступно скрывал. Если это еще не расказывали на лекции можно взять отсюда https://htmlacademy.ru/blog/boost/frontend/short-12 или просто кстыть с помощью `display: none`, а после лекции о доступности сделать правильно.

2021-02-10 22:12 UTC, dean992008 commented on css/style.css
> +  src: url(../fonts/PTSans.woff2), url(../font/PTSans.woff);
Это не исправлено. Ты скорее всего переименова файлы на своем компьютере, но они не попали в git. Нужно вынести шрифты, из репозитория закомитить, а потом снова венуть и закомитить. После этого на [этой странице](https://github.com/masha8709/1447971-sedona-30/tree/master/fonts), они должны стать маленкими буквами.

2021-02-11 04:54 UTC, masha8709 commented on css/style.css
> +  src: url(../fonts/PTSans.woff2), url(../font/PTSans.woff);
Ну всё, файлы с маленькой) Не поняла только, нужно ли в стилях само название шрифта с маленькой писать. Я сделала, вроде, всё работает.

2021-02-11 15:32 UTC, dean992008 commented on css/style.css
> +  src: url(../fonts/PTSans.woff2), url(../font/PTSans.woff);
Нет, `font-family` не нужно. 
Для справки: Почему мы так с именами заморачиваемся, на разный ОС большим и маленкие буквы обработываются по разному, на Windows не учитывается регистр, а вот на Unix учитывается, и поэтому было приняло решение на уровне договоренстой все файлы называть маленкими буквами.

2021-02-11 15:34 UTC, dean992008 commented on css/style.css
> +  src: url(../fonts/PTSans.woff2), url(../font/PTSans.woff);
Да, все исправлено как надо. Ты модец! 
В будущем когда будем работать с консолями не нужно будет переносить файлы, будет команда `git mv` (Это где-то себе пометку сделай, она в будушем возможно понадобится).

2021-02-11 15:34 UTC, merged